"""fcm token

Revision ID: 06db49572d69
Revises: 8c07f0ba5a02
Create Date: 2025-02-22 21:30:39.905953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '06db49572d69'
down_revision: Union[str, None] = '8c07f0ba5a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bro', sa.Column('fcm_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('Bro', sa.Column('fcm_token_timestamp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bro', 'fcm_token_timestamp')
    op.drop_column('Bro', 'fcm_token')
    # ### end Alembic commands ###
