"""platform indication

Revision ID: 08172eac6b93
Revises: 06db49572d69
Create Date: 2025-02-23 09:23:35.924094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08172eac6b93'
down_revision: Union[str, None] = '06db49572d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bro', sa.Column('platform', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bro', 'platform')
    # ### end Alembic commands ###
