"""change new avatar to broup object

Revision ID: 11d92301c515
Revises: 08172eac6b93
Create Date: 2025-03-02 21:20:58.349453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d92301c515'
down_revision: Union[str, None] = '08172eac6b93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('new_avatar', sa.Boolean(), nullable=False))
    op.drop_column('Chat', 'new_avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chat', sa.Column('new_avatar', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Broup', 'new_avatar')
    # ### end Alembic commands ###
