"""adding replied_to on message for future use

Revision ID: 1554f541bbf3
Revises: 7444d0f5f272
Create Date: 2025-04-09 08:47:10.687573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1554f541bbf3'
down_revision: Union[str, None] = '7444d0f5f272'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('replied_to', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'replied_to')
    # ### end Alembic commands ###
