"""removing time checks since we are using ids now

Revision ID: 1c3b39403c3e
Revises: 3b7fcd589883
Create Date: 2025-04-27 19:54:59.628907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c3b39403c3e'
down_revision: Union[str, None] = '3b7fcd589883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Broup', 'last_message_received_time')
    op.drop_column('Broup', 'last_message_read_time')
    op.drop_column('Chat', 'last_message_read_time_bro')
    op.drop_column('Chat', 'last_message_received_time_bro')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chat', sa.Column('last_message_received_time_bro', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Chat', sa.Column('last_message_read_time_bro', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Broup', sa.Column('last_message_read_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('Broup', sa.Column('last_message_received_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
