"""changing columns around

Revision ID: 1dbe988ea16c
Revises: 6ac772a8535c
Create Date: 2025-02-05 21:25:19.099739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1dbe988ea16c'
down_revision: Union[str, None] = '6ac772a8535c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('broup_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('Chat', 'broup_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chat', sa.Column('broup_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('Broup', 'broup_name')
    # ### end Alembic commands ###
