"""cleanup of broup

Revision ID: 1f91734b59ae
Revises: 41646abf8776
Create Date: 2025-03-27 08:20:53.153704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f91734b59ae'
down_revision: Union[str, None] = '41646abf8776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Broup', 'new_members')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('new_members', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
