"""avatar tracking for bros in broups

Revision ID: 24e8c7789ef0
Revises: 1f91734b59ae
Create Date: 2025-03-28 21:26:43.827785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24e8c7789ef0'
down_revision: Union[str, None] = '1f91734b59ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('update_bros_avatar', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Broup', 'update_bros_avatar')
    # ### end Alembic commands ###
