"""move variables

Revision ID: 251e00385ee6
Revises: 2e3c16d1ef68
Create Date: 2025-02-09 08:54:04.744373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251e00385ee6'
down_revision: Union[str, None] = '2e3c16d1ef68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('broup_updated', sa.Boolean(), nullable=False))
    op.drop_column('Chat', 'broup_updated')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chat', sa.Column('broup_updated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Broup', 'broup_updated')
    # ### end Alembic commands ###
