"""read and receive indicators

Revision ID: 2e3c16d1ef68
Revises: d34a22c3f17b
Create Date: 2025-02-07 15:51:58.574498

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2e3c16d1ef68"
down_revision: Union[str, None] = "d34a22c3f17b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Broup", sa.Column("last_message_read_time", sa.DateTime(), nullable=False))
    op.add_column("Broup", sa.Column("last_message_received_time", sa.DateTime(), nullable=False))
    op.drop_column("Broup", "last_time_activity")
    op.add_column(
        "Chat", sa.Column("last_message_received_time_bro", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Chat", "last_message_received_time_bro")
    op.add_column(
        "Broup",
        sa.Column(
            "last_time_activity", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("Broup", "last_message_received_time")
    op.drop_column("Broup", "last_message_read_time")
    # ### end Alembic commands ###
