"""receive list on message objects with last message read id on broups

Revision ID: 3b7fcd589883
Revises: 1554f541bbf3
Create Date: 2025-04-26 16:21:30.456449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b7fcd589883'
down_revision: Union[str, None] = '1554f541bbf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('last_message_read_id', sa.Integer(), nullable=False, default=0, server_default="0"))
    op.add_column('Chat', sa.Column('last_message_read_id_chat', sa.Integer(), nullable=False, default=0, server_default="0"))
    op.add_column('Message', sa.Column('receive_remaining', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'receive_remaining')
    op.drop_column('Chat', 'last_message_read_id_chat')
    op.drop_column('Broup', 'last_message_read_id')
    # ### end Alembic commands ###
