"""avatar change indication

Revision ID: 4007c669ef6f
Revises: 7ce8c95770bb
Create Date: 2025-02-06 12:46:34.865340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4007c669ef6f"
down_revision: Union[str, None] = "7ce8c95770bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Broup", sa.Column("new_avatar", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Broup", "new_avatar")
    # ### end Alembic commands ###
