"""adding data type to data in messages

Revision ID: 41646abf8776
Revises: 64924b1bf776
Create Date: 2025-03-26 16:29:56.199873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41646abf8776'
down_revision: Union[str, None] = '64924b1bf776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('data_type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'data_type')
    # ### end Alembic commands ###
