"""message identifier strings added


Revision ID: 486ab5d3227d
Revises: 5cb906ab42ce
Create Date: 2025-07-16 10:24:10.549872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '486ab5d3227d'
down_revision: Union[str, None] = '5cb906ab42ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('message_identifier', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'message_identifier')
    # ### end Alembic commands ###
