"""removing a mistake

Revision ID: 587e85397093
Revises: 486ab5d3227d
Create Date: 2025-08-01 18:09:36.976636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '587e85397093'
down_revision: Union[str, None] = '486ab5d3227d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'message_identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('message_identifier', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
