"""add emoji reaction to broup

Revision ID: 5cb906ab42ce
Revises: 1c3b39403c3e
Create Date: 2025-07-06 09:01:30.097580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb906ab42ce'
down_revision: Union[str, None] = '1c3b39403c3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('emoji_reactions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Broup', 'emoji_reactions')
    # ### end Alembic commands ###
