"""remove obsolete variables

Revision ID: 617ba83f9d84
Revises: ceabc5736afb
Create Date: 2025-02-03 09:23:28.688364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "617ba83f9d84"
down_revision: Union[str, None] = "ceabc5736afb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Broup", "accepted")
    op.drop_column("Broup", "mute_timestamp")
    op.drop_column("Broup", "requested")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Broup", sa.Column("requested", sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column(
        "Broup",
        sa.Column("mute_timestamp", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    )
    op.add_column("Broup", sa.Column("accepted", sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
