"""adding default_avatar for broups

Revision ID: 81759bee68f3
Revises: f9a0b11f41b9
Create Date: 2025-02-03 11:51:09.018092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "81759bee68f3"
down_revision: Union[str, None] = "f9a0b11f41b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Broup", sa.Column("default_avatar", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Broup", "default_avatar")
    # ### end Alembic commands ###
