"""indication of bros that are updated

Revision ID: 8c07f0ba5a02
Revises: 0b56c2446eeb
Create Date: 2025-02-20 13:25:01.514699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c07f0ba5a02'
down_revision: Union[str, None] = '0b56c2446eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('update_bros', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Broup', 'update_bros')
    # ### end Alembic commands ###
