"""cleanup of variable

Revision ID: 8d1ab9302a74
Revises: ddcdc47484ea
Create Date: 2025-02-19 13:53:40.727705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d1ab9302a74'
down_revision: Union[str, None] = 'ddcdc47484ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('left', sa.Boolean(), nullable=False))
    op.drop_column('Broup', 'is_left')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('is_left', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('Broup', 'left')
    # ### end Alembic commands ###
