"""message_id to messages

Revision ID: ad94e7ee3e13
Revises: 1dbe988ea16c
Create Date: 2025-02-06 09:24:10.565414

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad94e7ee3e13"
down_revision: Union[str, None] = "1dbe988ea16c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Message", sa.Column("message_id", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Message", "message_id")
    # ### end Alembic commands ###
