"""adding private indicator

Revision ID: ceabc5736afb
Revises: 4980919af044
Create Date: 2025-01-31 11:54:57.884373

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ceabc5736afb"
down_revision: Union[str, None] = "4980919af044"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Broup", sa.Column("private", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Broup", "private")
    # ### end Alembic commands ###
