"""more indicators

Revision ID: d34a22c3f17b
Revises: 4007c669ef6f
Create Date: 2025-02-06 17:12:00.444521

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d34a22c3f17b"
down_revision: Union[str, None] = "4007c669ef6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Broup", sa.Column("new_messages", sa.Boolean(), nullable=False))
    op.drop_column("Broup", "new_avatar")
    op.add_column("Chat", sa.Column("broup_updated", sa.Boolean(), nullable=False))
    op.add_column("Chat", sa.Column("new_avatar", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Chat", "new_avatar")
    op.drop_column("Chat", "broup_updated")
    op.add_column(
        "Broup", sa.Column("new_avatar", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_column("Broup", "new_messages")
    # ### end Alembic commands ###
