"""adding delete to messages

Revision ID: d5ad714895e7
Revises: 587e85397093
Create Date: 2025-10-06 15:14:18.833950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5ad714895e7'
down_revision: Union[str, None] = '587e85397093'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('message_updates', sa.JSON(), nullable=True))
    op.add_column('Message', sa.Column('deleted', sa.Boolean(), nullable=True, server_default='false'))
    op.execute("UPDATE \"Message\" SET deleted = false")
    op.alter_column('Message', 'deleted', nullable=False)
    # ### end Alembic commands ###
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'deleted')
    op.drop_column('Broup', 'message_updates')
    # ### end Alembic commands ###
