"""adding deleted flag

Revision ID: d986e1f7110e
Revises: 8d1ab9302a74
Create Date: 2025-02-19 15:12:31.131497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd986e1f7110e'
down_revision: Union[str, None] = '8d1ab9302a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Broup', 'deleted')
    # ### end Alembic commands ###
