"""new member indication

Revision ID: ddcdc47484ea
Revises: 251e00385ee6
Create Date: 2025-02-12 13:06:00.641804

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ddcdc47484ea"
down_revision: Union[str, None] = "251e00385ee6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("Broup", sa.Column("new_members", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("Broup", "new_members")
    # ### end Alembic commands ###
