"""adding deleted flag

Revision ID: df8a3557d57c
Revises: d986e1f7110e
Create Date: 2025-02-19 15:26:34.519545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df8a3557d57c'
down_revision: Union[str, None] = 'd986e1f7110e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Broup', 'left')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('left', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
