version: '3.6'
services:
  api:
    build: .
    depends_on:
      - db
    networks:
      - default
    ports:
      - 5000:5000
    restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: testdb
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always