services:
  brocast_api:
    container_name: brocast_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - default
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ${SHARED_DIR}:/app/static/uploads/
      - ./app/migrations:/app/migrations
    command: "/bin/sh boot.sh"
    depends_on:
      - brocast_db
    links:
      - brocast_db

  brocast_db:
    container_name: brocast_db
    env_file: .env
    image: postgres:15.3
    networks:
      - default
    ports:
      - 5432:5432
    restart: always
    shm_size: 1g
    command:
      - "postgres"
      - "-c"
      - "max_connections=1000"
      - "-c"
      - "max_parallel_workers=32"
      - "-c"
      - "max_parallel_workers_per_gather=8"
      - "-c"
      - "shared_buffers=4096MB"

  redis:
    image: redis:7.0.10
    ports:
      - 6379:6379
    command:
      - redis-server

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - default
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${SHARED_DIR}:/app/static/uploads/
    depends_on:
      - redis
      - brocast_db
    command: "poetry run celery -A app.celery_worker.tasks worker -l info"

  cron_worker:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - default
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${SHARED_DIR}:/app/static/uploads/
    depends_on:
      - redis
      - brocast_db
    command: "python main_cron.py"
