version: '3.6'
services:
  api:
    container_name: api
    build: .
    networks:
      - default
    ports:
      - 5000:5000
    volumes: ['./:/app']
    restart: always
    links:
      - db

  db:
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: testdb
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always