version: '3.6'
services:
  api:
    container_name: api
    build: .
    networks:
      - default
    ports:
      - 5000:5000
    volumes: ['./:/app']
    restart: always
    links:
      - db
      - redis

  db:
    container_name: db
    env_file: .env
    image: postgres:latest
    networks:
      - default
    ports:
      - 5432:5432
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command:
      - redis-server
