"""removed the device type

Revision ID: 07cc036446ac
Revises: 6894e4416cfa
Create Date: 2021-12-09 13:51:19.893342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cc036446ac'
down_revision = '6894e4416cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bro', 'device_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bro', sa.Column('device_type', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
