"""added alias to broBros and broups

Revision ID: 21995a0eb6ec
Revises: 264bc9b4023e
Create Date: 2021-10-20 08:36:15.928222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21995a0eb6ec'
down_revision = '264bc9b4023e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BroBros', sa.Column('alias', sa.String(), nullable=True))
    op.add_column('Broup', sa.Column('alias', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Broup', 'alias')
    op.drop_column('BroBros', 'alias')
    # ### end Alembic commands ###
