"""removed foreign key

Revision ID: 264bc9b4023e
Revises: 5e3f94205cfa
Create Date: 2021-10-01 09:34:34.910835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264bc9b4023e'
down_revision = '5e3f94205cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('BroupMessage_broup_id_fkey', 'BroupMessage', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('BroupMessage_broup_id_fkey', 'BroupMessage', 'Broup', ['broup_id'], ['id'])
    # ### end Alembic commands ###
