"""added bro group object

Revision ID: 26720ded42e3
Revises: 45a21a7bf424
Create Date: 2021-08-30 08:12:55.376627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26720ded42e3'
down_revision = '45a21a7bf424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Broup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bro_id', sa.Integer(), nullable=True),
    sa.Column('bro_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('broup_name', sa.String(), nullable=True),
    sa.Column('broup_description', sa.String(), nullable=True),
    sa.Column('broup_colour', sa.String(), nullable=True),
    sa.Column('room_name', sa.String(), nullable=True),
    sa.Column('last_message_read_time_bro', sa.DateTime(), nullable=True),
    sa.Column('last_time_activity', sa.DateTime(), nullable=True),
    sa.Column('unread_messages', sa.Integer(), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=True),
    sa.Column('blocked_timestamps', sa.ARRAY(sa.DateTime()), nullable=True),
    sa.ForeignKeyConstraint(['bro_id'], ['Bro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Broup_last_message_read_time_bro'), 'Broup', ['last_message_read_time_bro'], unique=False)
    op.create_index(op.f('ix_Broup_last_time_activity'), 'Broup', ['last_time_activity'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Broup_last_time_activity'), table_name='Broup')
    op.drop_index(op.f('ix_Broup_last_message_read_time_bro'), table_name='Broup')
    op.drop_table('Broup')
    # ### end Alembic commands ###
