"""removed one time read since it's not needed

Revision ID: 45121d14a991
Revises: 82070cd9b0ea
Create Date: 2021-04-09 17:22:41.594479

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '45121d14a991'
down_revision = '82070cd9b0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_BroBros_last_message_read_time_bros_bro', table_name='BroBros')
    op.drop_column('BroBros', 'last_message_read_time_bros_bro')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BroBros', sa.Column('last_message_read_time_bros_bro', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_BroBros_last_message_read_time_bros_bro', 'BroBros', ['last_message_read_time_bros_bro'], unique=False)
    # ### end Alembic commands ###
