"""added a logging table

Revision ID: 45a21a7bf424
Revises: c1fd52b6095e
Create Date: 2021-07-29 09:28:40.787195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a21a7bf424'
down_revision = 'c1fd52b6095e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_from', sa.Text(), nullable=True),
    sa.Column('report_to', sa.Text(), nullable=True),
    sa.Column('messages', sa.Text(), nullable=True),
    sa.Column('report_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Log')
    # ### end Alembic commands ###
