"""changed blocked to mute in broup objects

Revision ID: 4ba50a63f008
Revises: 9f66cae00cf9
Create Date: 2021-11-02 18:18:04.747908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba50a63f008'
down_revision = '9f66cae00cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('mute', sa.Boolean(), nullable=True))
    op.drop_column('Broup', 'blocked')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('blocked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('Broup', 'mute')
    # ### end Alembic commands ###
