"""added unread messages column

Revision ID: 4c4ce8a129a8
Revises: f914810c7644
Create Date: 2021-06-01 11:24:27.795986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4ce8a129a8'
down_revision = 'f914810c7644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BroBros', sa.Column('unread_messages', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BroBros', 'unread_messages')
    # ### end Alembic commands ###
