"""adding textMessage to a message for clarity

Revision ID: 50557a2d2fd8
Revises: 79798e7c6e36
Create Date: 2021-05-27 17:17:10.537538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50557a2d2fd8'
down_revision = '79798e7c6e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('text_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'text_message')
    # ### end Alembic commands ###
