"""added a indicator for leaving the broups

Revision ID: 5b42b31a5733
Revises: 3d02e638d9e0
Create Date: 2021-11-30 10:11:43.540053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b42b31a5733'
down_revision = '3d02e638d9e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('left', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Broup', 'left')
    # ### end Alembic commands ###
