"""removed unique constraint

Revision ID: 5e3f94205cfa
Revises: e9c37c72072a
Create Date: 2021-09-30 09:13:39.217563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e3f94205cfa'
down_revision = 'e9c37c72072a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Broup_broup_id_key', 'Broup', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Broup_broup_id_key', 'Broup', ['broup_id'])
    # ### end Alembic commands ###
