"""also have to do it for normal chats like for description changes

Revision ID: 6894e4416cfa
Revises: 6d04e122cf31
Create Date: 2021-11-30 20:39:23.469542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6894e4416cfa'
down_revision = '6d04e122cf31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('info', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'info')
    # ### end Alembic commands ###
