"""added broup messages

Revision ID: 6b57417d70f8
Revises: 26720ded42e3
Create Date: 2021-09-10 10:36:22.944337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b57417d70f8'
down_revision = '26720ded42e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BroupMessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('broup_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('text_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['broup_id'], ['Broup.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['Bro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_BroupMessage_timestamp'), 'BroupMessage', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BroupMessage_timestamp'), table_name='BroupMessage')
    op.drop_table('BroupMessage')
    # ### end Alembic commands ###
