"""added info indicator to broup messages

Revision ID: 6d04e122cf31
Revises: 5b42b31a5733
Create Date: 2021-11-30 19:50:56.390481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d04e122cf31'
down_revision = '5b42b31a5733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BroupMessage', sa.Column('info', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BroupMessage', 'info')
    # ### end Alembic commands ###
