"""added chat descrption

Revision ID: 6ea95814d54c
Revises: 45064f47ab31
Create Date: 2021-06-03 19:33:34.855605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea95814d54c'
down_revision = '45064f47ab31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BroBros', sa.Column('chat_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BroBros', 'chat_description')
    # ### end Alembic commands ###
