"""added registration id to bro

Revision ID: 79798e7c6e36
Revises: be3cb9536977
Create Date: 2021-05-11 17:57:32.367488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79798e7c6e36'
down_revision = 'be3cb9536977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bro', sa.Column('registration_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bro', 'registration_id')
    # ### end Alembic commands ###
