"""add bromotion to the bros

Revision ID: 79c00d41dafa
Revises: 7eeb5375773b
Create Date: 2019-12-19 22:28:31.901779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79c00d41dafa'
down_revision = '7eeb5375773b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bro', sa.Column('bromotion', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_Bro_bromotion'), 'Bro', ['bromotion'], unique=False)
    op.drop_index('ix_Bro_bro_name', table_name='Bro')
    op.create_index(op.f('ix_Bro_bro_name'), 'Bro', ['bro_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Bro_bro_name'), table_name='Bro')
    op.create_index('ix_Bro_bro_name', 'Bro', ['bro_name'], unique=True)
    op.drop_index(op.f('ix_Bro_bromotion'), table_name='Bro')
    op.drop_column('Bro', 'bromotion')
    # ### end Alembic commands ###
