"""add registration id to a bro for notifications

Revision ID: 7eeb5375773b
Revises: 2bd31204deec
Create Date: 2019-12-15 17:09:41.573765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eeb5375773b'
down_revision = '2bd31204deec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bro', sa.Column('registration_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bro', 'registration_id')
    # ### end Alembic commands ###
