"""added roomname to the brosbro and last time read

Revision ID: 82070cd9b0ea
Revises: 1e39cd176d63
Create Date: 2021-04-09 15:26:44.900300

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82070cd9b0ea'
down_revision = '1e39cd176d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bro', 'last_message_read_time')
    op.add_column('BroBros', sa.Column('last_message_read_time_bro', sa.DateTime(), nullable=True))
    op.add_column('BroBros', sa.Column('last_message_read_time_bros_bro', sa.DateTime(), nullable=True))
    op.add_column('BroBros', sa.Column('room_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_BroBros_last_message_read_time_bro'), 'BroBros', ['last_message_read_time_bro'], unique=False)
    op.create_index(op.f('ix_BroBros_last_message_read_time_bros_bro'), 'BroBros', ['last_message_read_time_bros_bro'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_BroBros_last_message_read_time_bros_bro'), table_name='BroBros')
    op.drop_index(op.f('ix_BroBros_last_message_read_time_bro'), table_name='BroBros')
    op.drop_column('BroBros', 'room_name')
    op.drop_column('BroBros', 'last_message_read_time_bros_bro')
    op.drop_column('BroBros', 'last_message_read_time_bro')
    op.add_column('Bro', sa.Column('last_message_read_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
