"""added device type to the bro

Revision ID: 8d8029d633d8
Revises: 6ea95814d54c
Create Date: 2021-07-20 20:27:13.937258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d8029d633d8'
down_revision = '6ea95814d54c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bro', sa.Column('device_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bro', 'device_type')
    # ### end Alembic commands ###
