"""added message object

Revision ID: 8f6993dfb0d1
Revises: afe4d9070f9e
Create Date: 2021-03-29 22:12:21.877675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f6993dfb0d1'
down_revision = 'afe4d9070f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bro_bros_id', sa.Integer(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bro_bros_id'], ['BroBros.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['Bro.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['Bro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Message_timestamp'), 'Message', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Message_timestamp'), table_name='Message')
    op.drop_table('Message')
    # ### end Alembic commands ###
