"""added broup admin indicators

Revision ID: 9f66cae00cf9
Revises: 21995a0eb6ec
Create Date: 2021-10-23 16:40:30.450089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f66cae00cf9'
down_revision = '21995a0eb6ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Broup', sa.Column('bro_admin_ids', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Broup', 'bro_admin_ids')
    # ### end Alembic commands ###
