"""added bro and brosbro to keep track of your bros

Revision ID: afe4d9070f9e
Revises: 
Create Date: 2021-03-29 18:03:39.123141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe4d9070f9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Bro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bro_name', sa.Text(), nullable=True),
    sa.Column('bromotion', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Bro_bro_name'), 'Bro', ['bro_name'], unique=False)
    op.create_index(op.f('ix_Bro_bromotion'), 'Bro', ['bromotion'], unique=False)
    op.create_table('BroBros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bro_id', sa.Integer(), nullable=True),
    sa.Column('bros_bro_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bro_id'], ['Bro.id'], ),
    sa.ForeignKeyConstraint(['bros_bro_id'], ['Bro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BroBros')
    op.drop_index(op.f('ix_Bro_bromotion'), table_name='Bro')
    op.drop_index(op.f('ix_Bro_bro_name'), table_name='Bro')
    op.drop_table('Bro')
    # ### end Alembic commands ###
