"""adding data to messages

Revision ID: b01281a7e596
Revises: d117cba5172d
Create Date: 2022-07-29 21:04:09.889867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b01281a7e596'
down_revision = 'd117cba5172d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('data', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Message', 'data')
    # ### end Alembic commands ###
