"""added connection to bros

Revision ID: b2cdaf79dba4
Revises: 8f6993dfb0d1
Create Date: 2021-03-29 22:13:51.445183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2cdaf79dba4'
down_revision = '8f6993dfb0d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Bro', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Bro', 'last_message_read_time')
    # ### end Alembic commands ###
