"""removed obsolete columns on message, sender and receipient is enough

Revision ID: be3cb9536977
Revises: 45121d14a991
Create Date: 2021-04-09 17:42:17.123277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be3cb9536977'
down_revision = '45121d14a991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Message_bro_bros_id_fkey', 'Message', type_='foreignkey')
    op.drop_column('Message', 'bro_bros_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Message', sa.Column('bro_bros_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Message_bro_bros_id_fkey', 'Message', 'BroBros', ['bro_bros_id'], ['id'])
    # ### end Alembic commands ###
