"""added mute for normal chats

Revision ID: d44f764281ca
Revises: 4ba50a63f008
Create Date: 2021-11-02 20:10:07.224011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44f764281ca'
down_revision = '4ba50a63f008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BroBros', sa.Column('mute', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BroBros', 'mute')
    # ### end Alembic commands ###
