"""add table message so bros can message each other

Revision ID: f269daa6d3b2
Revises: 975398824c89
Create Date: 2019-12-05 18:13:48.379965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f269daa6d3b2'
down_revision = '975398824c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bro', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bro', 'last_message_read_time')
    # ### end Alembic commands ###
