"""added a chat colour

Revision ID: f914810c7644
Revises: 900e62e0c894
Create Date: 2021-05-28 13:56:33.570377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f914810c7644'
down_revision = '900e62e0c894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('BroBros', sa.Column('chat_colour', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('BroBros', 'chat_colour')
    # ### end Alembic commands ###
