# local secret
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
  namespace: cast-of-bro
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # password
  POSTGRES_DB: ZGF0YWJhc2U= # database