apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  namespace: cast-of-bro
  labels:
    app: flaskapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      namespace: cast-of-bro
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: bro_cast:1.74
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "250m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: flask-secret
          env:
            - name: POSTGRES_URL
              value: service-postgres.cast-of-bro.svc.cluster.local
            - name: POSTGRES_PORT
              value: "5432"
            - name: REDIS_URL
              value: redis-service.cast-of-bro.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  namespace: cast-of-bro
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: LoadBalancer