apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi-deployment
  namespace: cast-of-bro
  labels:
    app: flaskapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      namespace: cast-of-bro
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: bro_cast:0.74
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "128Mi"
          env:
            - name: POSTGRES_URL
              value: service-postgres.cast-of-bro.svc.cluster.local
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: database
            - name: REDIS_URL
              value: redis-service.cast-of-bro.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  namespace: cast-of-bro
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: LoadBalancer