apiVersion: v1
kind: Service
metadata:
  name: service-postgres
  namespace: cast-of-bro
  labels:
    name: postgres
spec:
  ports:
    - port: 5432
  selector:
    app: database
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-db-claim
  namespace: cast-of-bro
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cast-of-bro
  name: deployment-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      namespace: cast-of-bro
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 180
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - name: tcp-5432
              containerPort: 5432
          env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: password
          - name: POSTGRES_DB
            value: database
          volumeMounts:
            - name: data-storage-volume
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              cpu: "50m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: data-storage-volume
          persistentVolumeClaim:
            claimName: postgres-db-claim