apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: cast-of-bro
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-api
  namespace: cast-of-bro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      namespace: cast-of-bro
      labels:
        app: redis
    spec:
      containers:
        - name: redis-api
          image: redis
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "500m"
              memory: "5Gi"
            limits:
              cpu: "1"
              memory: "10Gi"